name: Pull Request Reviewers
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked     
jobs:
  reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR Reviewers
        uses: rhs/add-reviewer-gh-action@1.0.6
        with: 
          reviewers: brockenbrough
          token: ${{ secrets.GH_TOKEN }}